wopian/kitsu

src/util/serialise/index.js
src/util/serialise/index.spec.js

Removes alternative check for type attribute on relationship elements.
The check is superfluous, ID check is necessary.
Fixes #84.

Fix validation of relationship serialisation

---

package.json
packages/kitsu/package.json
yarn.lock

`size-limit` switched to webpack 4 and broke importing of modules (works fine in usage). Webpack 4 released undocumented so not worth trying to find why.
Also probably need to look for an alternative to `size-limit` - webpack 4 is even bigger than 3 for our dev dependencies.

build(kitsu): fix size-limit errors (closes #138)

---

packages/kitsu/index.d.ts

Currently the `Kitsu` class is exported using
```ts
export = Kitsu;
```
which means, when using it, we've to import it using CommonJS `require`:
```ts
import Kitsu = require("kitsu");
```
But if we export it using
```ts
export default Kitsu;
```
we can import it like this:
```ts
import Kitsu from "kitsu"
```

Improve kitsu typings to prevent CommonJS style require imports

---

packages/kitsu-core/src/serialise/index.js

I fixed an operator that should be logical and but was written as bitwise and. This causes issues when `node` is `null`. If the code was written properly, the `node !== null` expression would short-circuit the `&&` operator and `node.constructor` would not be evaluated. However, with `&` both expressions are evaluated, raising an error when trying to reference the `constructor` property on `null`.

fix(kitsu-core): changed & to &&

---

packages/kitsu/src/index.js
packages/kitsu/src/index.spec.js

Solves #132 
This should allow access to the axios interceptors functionality via the base Kitsu class.  Thus creating similar usage as the axios documentation, but on the Kitsu object.

Alias interceptors from axios to Kitsu

---

packages/kitsu-core/src/serialise/index.js
packages/kitsu-core/src/serialise/index.spec.js

I've some singular API endpoints such as "task" and the library pluralizes types/models by default. here is a quick demo of the issue. [codesandbox](https://codesandbox.io/s/reverent-margulis-ysp8v?file=/src/App.js)
This PR aims to solve this behavior and make the usage of pluralise optional.

feat(kitsu-core): optional pluralisation during serialisation

---

packages/kitsu-core/src/serialise/index.js

Thanks for the awesome library.
I'm currently using it in a TypeScript project with instantiated objects of a different type (i.e., `const user = new User()`). The validation that checks the object's prototype parent fails unless I clone the object (by passing in something like `{ ...user }`). I changed the validation to allow objects further down the prototype chain.
Let me know if I'm missing the justification. Thanks again for your time.

feat(kitsu-core): allow longer prototype chain on serialise

---

packages/kitsu-core/src/serialise/index.js

Re-opening due to a premature merge!
Thanks for the awesome library.
I'm currently using it in a TypeScript project with instantiated objects of a different type (i.e., const user = new User()). The validation that checks the object's prototype parent fails unless I clone the object (by passing in something like { ...user }). I changed the validation to allow objects further down the prototype chain.
Let me know if I'm missing the justification. Thanks again for your time.

fix(kitsu-core): allow longer prototype chain on serialise

---

README.md
config/presets.js
package.json
packages/kitsu-core/README.md
packages/kitsu-core/package.json
packages/kitsu/README.md
packages/kitsu/package.json

Applies to `^10.x` only (currently pre-release) - `^9.x` will retain node 10 support
Node 10 is in the last stages of Maintenance LTS and will hit EOL in April 2021

build: drop node 10 support

---

.github/workflows/jest.yml

Reverts wopian/kitsu#492
Release was removed from GitHub and now breaks CI builds (see https://github.com/wopian/kitsu/pull/493)

Revert "build: update amancevice/setup-code-climate action to v1"

---

packages/kitsu-core/src/deattribute/index.js
packages/kitsu-core/src/deserialise/index.js
packages/kitsu-core/src/deserialise/index.spec.js
packages/kitsu-core/src/linkRelationships/index.js
packages/kitsu-core/src/serialise/index.js

fix(kitsu-core): use typeof instead of constructor comparison for checking if Object

---

.github/workflows/ci.yml
README.md
config/presets.js
package.json
packages/kitsu-core/README.md
packages/kitsu-core/package.json
packages/kitsu/README.md
packages/kitsu/package.json

Node 12 reaches end of life at the end of April 2022. Library is now tested with Node 14, 16 and 18.

build: drop node 12 support

---

packages/kitsu-core/src/deserialise/index.js
packages/kitsu-core/src/deserialise/index.spec.js

I ran into this issue where resource relationships would not deserialise correctly, due to being removed from `includes`.
According to the git history of AMS, this is inteded behaviour https://github.com/rails-api/active_model_serializers/commit/f4bb4c81b0a7925104fd55143cd6f888de667fc6
It seems to be described by this line in the jsonapi spec:
`A compound document MUST NOT include more than one resource object for each type and id pair.`
(more on the topic https://discuss.jsonapi.org/t/why-is-included-an-array/76/4)
With this very minor change, this edge-case should be handled correctly.

fix(kitsu-core): fix deserialisation of relationships from primary data

---

package.json

Publishing config to npm is deprecated by Renovate

ci: update renovate config to repository

---

packages/kitsu-core/src/deserialise/index.js
packages/kitsu-core/src/deserialise/index.spec.js
packages/kitsu-core/src/linkRelationships/index.js

Before this fix, this error would occasionally pop up
```
TypeError: Cannot read properties of undefined (reading 'links')
65 |   const cache = previouslyLinked[`${resource.type}#${resource.id}`]
66 |   data[key].data = cache || link(resource, included, previouslyLinked)
> 67 |   if (data.relationships[key].links) data[key].links = data.relationships[key].links
|                               ^
68 |   delete data.relationships[key]
69 | }
70 |
at links (packages/kitsu-core/src/linkRelationships/index.js:67:31)
at linkObject (packages/kitsu-core/src/linkRelationships/index.js:123:7)
at deserialiseArray (packages/kitsu-core/src/deserialise/index.js:14:13)
at deserialiseArray (packages/kitsu-core/src/deserialise/index.js:61:48)
at Object.<anonymous> …
```

fix(kitsu-core): fix inability to link relationship links on circular resources

---

packages/kitsu-core/package.json
packages/kitsu/package.json

If you wish to be listed on the npm package page @pedep for your multiple contributions 🥇 
Edit: Actually looks like npm no longer reads the `contributors` entry, npm only shows myself these days 🤔

docs: list pedep as a contributor

---

packages/kitsu-core/src/deserialise/index.js
packages/kitsu-core/src/deserialise/index.spec.js

This issue specifically occours if Article1 and Article2 are deserialized in primary data, but also
references directly by a relationship of Article1, such as Author1
This makes Article1 deserialize first, then its relationship Author1 is
deserialised, along with its relationships Article1 and Article 2
Once the entire chain is complete in Article1, Article2 is deserialised
in the main data, but due to being mutated by the prior deserialisation,
it has no items in its relationships key
~~Honestly im kind of stumped by this one. I'm attempting a minor rewrite to use
immutable/functional style, but that would have a pretty major impact on the rest of kitsu-core.~~
Having spent a day with the issue, and trying some dark redux-style magick with no success, the solution turned out a lot …

fix(kitsu-core): prevent relationship mutation during multi-circular deserialisation

---

packages/kitsu-core/src/deserialise/index.spec.js
packages/kitsu-core/src/linkRelationships/index.js

same as with links only: https://github.com/wopian/kitsu/blob/d261d4c161f69f98f3f354455a3cc73efddfab82/packages/kitsu-core/src/deserialise/index.spec.js#L161-L188
[Section 5.2.4 of documentation](https://jsonapi.org/format/#document-resource-object-relationships) states "A “relationship object” MUST contain at least one of the following: `links`, `data` or `meta`", so meta-only relationships should be just as valid as links only.
With this we PR support all cases.
The test-case for links, meta and data at the same time is handled indirectly by other specs, such as here:
https://github.com/wopian/kitsu/blob/d261d4c161f69f98f3f354455a3cc73efddfab82/packages/kitsu-core/src/deserialise/index.spec.js#L791-L852

fix(kitsu-core): deserialize meta only relationships

---

packages/kitsu-core/src/query/index.js
packages/kitsu-core/src/query/index.spec.js

I'm not sure this is the way you would prefer to serialize arrays by default, but i personally think its better than the current behaviour.
`query` serializes arrays the same way a regular `<select multiple>` would.`
e.g. both
```
<select name="filter[id_in][]" multiple>
<option value="1" selected> New York </option>
<option value="2" selected> Boston </option>
</select>
```
and
```
query({filter: {id_in: [1,2]}})
```
should result in the following query
```
filter[id_in][]=1&filter[id_in][]=2
```
```
query({filter: {id_in: [1,2]}})
```
results in this query:
```
filter[id_in][0]=1&filter[id_in][1]=2
```

fix(kitsu-core): build list queryparams

---

packages/kitsu-core/src/serialise/index.js
packages/kitsu-core/src/serialise/index.spec.js
packages/kitsu/src/post.spec.js

closes #800
Issue stems from `isValid` being run before `let data = { type }`, making the `isValid` function assume the payload is empty even though it is not.
The spec allows type-only post bodies https://jsonapi.org/format/#crud-creating
I decided to just add another check for `method == 'POST'`, rather than something like this:
```diff
function serialiseRootObject (type, payload, method, options) {
-  isValid(false, type, payload, method)
+  isValid(false, type, {...payload, type: type}, method)
type = options.pluralTypes(options.camelCaseTypes(type))
let data = { type }
```
since this change would the `${method} requires an ID for the ${type} type` error raise on empty PATCH bodies instead of `${method} requires an object or array body` error

fix(kitsu-core): Allow empty POST body

---

packages/kitsu-core/src/query/index.js
packages/kitsu-core/src/query/index.spec.js
packages/kitsu/src/index.js
packages/kitsu/src/index.spec.js

Resolves discussion from https://github.com/wopian/kitsu/pull/781
This PR aims to introduce the following:
1. Parse key names like `id_in[]` and `id_in][` and ensure they appear intuitively in the query (`filter[id_in][]`)
Previous behaviour would generate keys like `filter[id_in[]]`, requiring unintuitive keys `id_in][` in order to achieve the expected behaviour.
2. Make the `query` method configurable, by allowing an option to be passed to the  `Kitsu` class constructor
2.1  Allow the user to switch between `traditional` (current behaviour) and `modern` mode. Modern mode allows to automatic generation of array style keys when passing an array to `params`, instead of having to explicitly declare them: 
traditional `api.get('anime', {filter: {id_in[]: [1,2]}}) -> …

feat(kitsu): Configurable modern query serializer

---

packages/kitsu/src/index.js

Kitsu.post was missing config.axiosOptions in the JSDoc definitions. This adds the missing type.

fix: correct the typing for config on post

---

packages/kitsu/package.json

Fix types issue

---

package.json
packages/kitsu/package.json
packages/kitsu/src/index.js
yarn.lock

Closes #978
This bumps axios to 0.28.1 due to [Axios Cross-Site Request Forgery Vulnerability](https://github.com/advisories/GHSA-wf5p-g6vw-rhxx).
The `size-limit` needed to be adjusted from `13 kb` to `14 kb`
The `paramsSerializer` configuration needs to be an object with `serialize` set to the function.

fix(kitsu): update dependency axios to v0.28.1 to address CVE-2023-45857

---

README.md
packages/kitsu-core/src/deserialise/index.spec.js
packages/kitsu/MIGRATING.md
packages/kitsu/README.md
packages/kitsu/example/auth.js
packages/kitsu/package.json
packages/kitsu/src/index.js
packages/kitsu/src/index.spec.js
packages/kitsu/types/index.d.ts
specification/getCollection/jsonapi.js
specification/getCollection/kitsu.js
specification/getCollectionWithIncludes/jsonapi.js
specification/getCollectionWithIncludes/kitsu.js

Kitsu switched domains in 2024. The API endpoint redirects to kitsu.app, but we should transition to it by default.

chore: update the default baseURL to the new kitsu domain

---

packages/kitsu/src/delete.spec.js
packages/kitsu/src/get.spec.js
packages/kitsu/src/index.js
packages/kitsu/src/patch.spec.js
packages/kitsu/src/post.spec.js
packages/kitsu/src/request.spec.js

Thanks for Kitsu! It's awesome :-)
We wanted to know whether the HTTP status code was a 206 to know if we'd received a partial response - and were wondering if you'd be willing to land this tweak to add it to the result :-)
_Also, on looking a bit closer, I noticed that this isn't in the other methods in the same file - would be willing to add it more places if that's helpful_ :slightly_smiling_face:

Add HTTP status code to kitsu responses
